feat(defaultheader, defaultfooter, defaultcarousel, page.tsx): implem…
devosu/research-mentorship-frontend pull request #17
Opened 2024-06-08 00:53 UTC by trev-org04

implemented home page

Implemented home page with header, footer, and carousel using TailwindCSS

2024-06-08 01:05 UTC, KemingHe requested changes
Awesome job first of all, I would request a bit of refactoring to be more NextJS-native in terms of importing and optimization. See you in the coversation.

2024-06-08 01:05 UTC, KemingHe commented on src/components/DefaultHeader.tsx
> +import logo from '../../public/images/logo.png';
- [ ] Fix needed: don't import/specify path, instead, NextJS auto-recognizes public dir resources. 
- [ ] Read more here: https://nextjs.org/docs/app/building-your-application/optimizing/static-assets

2024-06-08 01:05 UTC, KemingHe commented on src/components/DefaultHeader.tsx
> +import logo from '../../public/images/logo.png';
TLDR: relative import path bad.

2024-06-08 01:05 UTC, KemingHe commented on src/components/DefaultHeader.tsx
> +					<a
- [ ] Fix: use NextJS's Link instead of a tag.

2024-06-08 01:05 UTC, KemingHe commented on tailwind.config.js
I wonder if this can be written as .ts?

Also, what about using and appending to the original tailwind css config?

2024-06-08 01:07 UTC, KemingHe commented
@trev-org04 see your amazing preview deployment here:
https://frontend-preview-app-wrhx7cwynq-uc.a.run.app/

2024-06-08 01:14 UTC, KemingHe commented on tailwind.config.js
- [ ] @KemingHe will be reverting this change and updating the tailwind routes withe the latest tsconfig setup.

2024-06-08 05:35 UTC, trev-org04 commented
@KemingHe Pushed changes that address your comments and requesting another review at your earliest convenience

2024-06-28 06:12 UTC, KemingHe commented on src/components/DefaultRegisterForm.tsx
> +        console.log('password: ' + password);
@trev-org04 
- [ ] Please look into this and resolve the security weakpoint

2024-07-01 03:49 UTC, KemingHe commented
@trev-org04 Deployment is broken due to the outdated Firebase config that works in local dev but out compatible with Docker and Cloud Run, will update you soon via my fix on I and Jerry's branch `refactor-onlycomponentsupdate-keminghe`.

2024-07-10 19:42 UTC, KemingHe approved these changes
Fixed everything fixable so far. **I foresee another 2 weeks at least to polish this.** Being realistic.

2024-07-10 19:44 UTC, merged